name: Deploy Astro Site To GitHub Pages
# description: Adapted workflow for our personal use case using astro with nx
# author: richardblondet

# Allow all jobs to: 
# - read the repo contents 
# - create a pages deployment
# - create an id-token deployment
permissions:
  contents: write

# Workflow Events
on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
    # If you run this workflow from a browser you must enter values for the required inputs manually before the workflow will run.
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

  push:
    branches: [ 'gh-pages' ]
    # branches: [ 'bugfix/github-pages-deploy-workflow' ]
    paths-ignore:
      - 'public_html/**'
    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODEJS_VERSION: 16.19.0
      BUILD_ARTIFACT_LOCATION: dist/apps/web
      DESTINATION_PATH: public_html
      CNAME: richardblondet.com
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} CI Action
      CI_COMMIT_MESSAGE: "CI: Updated public_html automatically"
      CI_GIT_USERNAME: richardblondet
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install web dependencies
        run: npm install

      - name: Build web app
        run: npx nx build web 

      - name: Add domain cname file
        run: echo "$CNAME" >> $BUILD_ARTIFACT_LOCATION/CNAME

      - name: Copy built artifact to public folder
        run: cp -a "$BUILD_ARTIFACT_LOCATION/." "$DESTINATION_PATH"

      - name: Upload built artifat
        uses: actions/upload-pages-artifact@v1
        with:
          path: "${{ env.DESTINATION_PATH }}/"

      - name: Update public_html with built artifact
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_GIT_USERNAME }}@users.noreply.github.com"
          git pull && git checkout gh-pages
          git checkout master -- ${{ env.DESTINATION_PATH }}
          git add ${{ env.DESTINATION_PATH }}
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
